version: "2"
checks:
  method-lines:
      config:
        threshold: 40
plugins:
  duplication:
    enabled: true
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
  method-count:
    enabled: false
exclude_patterns:
  - backend/
  - android-client/
  - "**/coverage"
  - "**/.husky"
  - "**/.next"
  - "**/cypress"
  - "**/node_modules/"
  - "**/*.d.ts"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.test.ts"
  - "**/*.test.tsx"
