version: "2"
plugins:
  duplication:
    enabled: true
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
  method-count:
    enabled: false
exclude_patterns:
  - backend/
  - android-client/
