version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
- frontend/node_modules/
- backend/