FROM ruby:3.1.2-alpine

# dependencies
RUN apk add --no-cache \
  git build-base postgresql-dev \
  nodejs npm tzdata less graphviz \
  font-noto fontconfig fc-cache -f

# install recent yarn
RUN npm install -g yarn

# install bundler
RUN gem install bundler

# config home environment
WORKDIR /app

COPY Gemfile Gemfile.lock /app/

RUN gem install bundler
RUN bundle config set --local path 'vendor/bundle'
RUN bundle install --binstubs

ENV PATH="$PATH:/app/bin"
